version: '3.7'

services:
  db:
    image: mariadb:latest
    container_name: ${APP_NAME}_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - sql:/var/lib/mysql/
    networks:
      symfony_net:
        ipv4_address: 172.20.0.2

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ${APP_NAME}_phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      symfony_net:
        ipv4_address: 172.20.0.3

  php:
    container_name: ${APP_NAME}_php
    restart: always
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile-php
    environment:
      APP_ENV: prod
      APP_DEBUG: 0
    volumes:
      - files:/var/www/symfony
    networks:
      symfony_net:
        ipv4_address: 172.20.0.4

  nginx:
    container_name: ${APP_NAME}_nginx
    restart: always
    depends_on:
      - php
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - files:/var/www/symfony
    networks:
      symfony_net:
        ipv4_address: 172.20.0.5

networks:
  symfony_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  files:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${PATH_TO_PROJECT}/files
  sql:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${PATH_TO_PROJECT}/database
